### ISSUE TITLE
Tests failing due to missing API key for weather API

### ISSUE THREAD

**Issue by cancan101** [betodealmeida/shillelagh#230]
Look like something wrong with the `SHILLELAGH_ADAPTER_KWARGS` env var. Either he env var is missing entirely or you are missing the `api_key` for the weather api.

**Comment by cancan101** [comment]
If you won't want to put a real API key in GH, I would suggest using a dummy key and then mocking out the http responses.

**Comment by betodealmeida** [comment]
Are these the integration tests? The integration tests use a real API key reading from GitHub secrets, since they talk to the actual service, but they will fail for people who are not admins — otherwise one could fork the repo and create a malicious branch that sent the secrets somewhere they control.

The unit tests should all mock the requests, though, if those are failing then we should fix them.

**Comment by cancan101** [comment]
Yes, I think it was an integration test (https://github.com/betodealmeida/shillelagh/runs/5855843247?check_suite_focus=true). It looks like the issue is resolved now (at least recent PRs seem fine). Not sure if you changed something on your end?
